spring.datasource.url=jdbc:postgresql://dpg-d75pj6k50q8c73b5ttv0-a:5432/flight_db_qefj?sslmode=require
spring.datasource.username=flight_db_qefj_user
spring.datasource.password=89kByhQdx7DWbRLposkf9AnPaQ14EL01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=${PORT:8080}