# =============================================
# Application Name & Profile
# =============================================
spring.application.name=flight-delay-alert-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# =============================================
# Common Settings (sab profiles ke liye)
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.port=${PORT:10000}                  # Render ke liye 10000 best hai

# =============================================
# PRODUCTION - PostgreSQL (Render)
# =============================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate optimization for Render
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# =============================================
# MAIL Configuration
# =============================================
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true