spring.application.name=flight-delay-alert-api

spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:35542/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=OLMToUpRFBaDCYHGzCPomkPUBKuDiQMo

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080